import React from 'react';

export const general = {
  heat: [
    {
      title: 'Go to the hospital',
      body: 'If the person is unconscious.',
      imgUrl: require('../assets/images/108.png'),
    },
    {
      title: 'Get out of the heat',
      body: 'Immediately move the patient under a cool shade.',
      imgUrl: require('../assets/images/tree-shade.jpg'),
    },
    {
      title: 'Lie down',
      body: 'Get the patient in a comfortable position.Elevate the feet.Remove any tight clothing.',
      imgUrl: require('../assets/images/heat-steps.jpg'),
    },
    {
      title: 'Lower the temperature',
      body: 'Use fan or apply cold compresses to the skin.',
      imgUrl: require('../assets/images/icepack.jpg'),
    },
    {
      title: 'Rehydrate',
      body: 'Have the victim drink fluids.Water can be used for rehydration.',
      imgUrl: require('../assets/images/water.jpg'),
    },
  ],
  fever: [
    {
      title: 'Seek medical advice',
      body: 'If someone with fever has 1.Difficulty breathing\n2.Chest pain\n3.Repeated vomiting ',
      imgUrl: require('../assets/images/108.png'),
    },
    {
      title: 'Stay hydrated',
      body: 'Drink plenty of fluids to stay hydrated.',
      imgUrl: require('../assets/images/water.jpg'),
    },
    {
      title: 'Cover the patient',
      body: 'Use a light blanket if the patient feels chilled, until the chills end.',
      imgUrl: require('../assets/images/cover.jpg'),
    },
    {
      title: 'Apply wash cloth',
      body: 'Use a wet wash cloth to lower the body temperature',
      imgUrl: require('../assets/images/feverwashcloth.jpg'),
    },
    {
      title: 'Take antibiotics(as adviced)',
      body: 'Take acetaminophen (Tylenol, others) or ibuprofen (Advil, Motrin IB, others). Follow the directions on the label.',
      imgUrl: require('../assets/images/ibuprofen.jpg'),
    },
  ],
  bones: [
    {
      title: 'Stop any bleeding',
      body: 'If they’re bleeding, elevate and apply pressure to the wound using a sterile bandage, a clean cloth, or a clean piece of clothing.',
      imgUrl: require('../assets/images/bleeding.jpg'),
    },
    {
      title: 'Immobilize the injured area',
      body: 'Wash the wound with water and apply pressure with sterile gauze, a bandage, or a clean cloth.',
      imgUrl: require('../assets/images/support.jpg'),
    },
    {
      title: 'Apply cold to the area',
      body: 'Wrap an ice pack or bag of ice cubes in a piece of cloth and apply it to the injured area for up to 10 minutes at a time.',
      imgUrl: require('../assets/images/icepack.jpg'),
    },
    {
      title: 'Treat them for shock',
      body: 'Help them get into a comfortable position, encourage them to rest, and reassure them. Cover them with a blanket or clothing to keep them warm.',
      imgUrl: require('../assets/images/recovery1.png'),
    },
    {
      title: 'Get professional help',
      body: 'Call 911 or help them get to the emergency department for professional care.',
      imgUrl: require('../assets/images/108.png'),
    },
  ],
  heart: [
    {
      title: 'Call 108 ambulance',
      body: "Don't ignore the risks of heart attack.Try to get the patient to the nearest hospital as soon as possible.",
      imgUrl: require('../assets/images/108.png'),
    },
    {
      title: 'Make victim comfortable',
      body: 'Loosen tight clothng,lay down the victim.',
      imgUrl: require('../assets/images/recovery1.png'),
    },
    {
      title: 'Begin CPR',
      body: "If the person isn't breathing or you don't find a pulse.",
      imgUrl: require('../assets/images/cpr.jpg'),
    },
  ],
  cuts: [
    {
      title: 'Go to the hospital',
      body: 'If the cut is severe and large with high chances of infection.',
      imgUrl: require('../assets/images/minor-cut.jpg'),
    },
    {
      title: 'Rinse with water',
      body: 'Wash the wound with water and apply pressure with sterile gauze, a bandage, or a clean cloth.',
      imgUrl: require('../assets/images/wash-hand.jpg'),
    },
    {
      title: 'Stop bleeding',
      body: 'If blood soaks through the bandage, place another bandage on top of the first and keep applying pressure.',
      imgUrl: require('../assets/images/bleeding.jpg'),
    },
    {
      title: 'Apply bandage',
      body: 'When bleeding stops, cover the wound with a new, clean bandage.',
      imgUrl: require('../assets/images/bandage.jpg'),
    },
  ],
  shock: [
    {
      title: 'Call 108 ambulance',
      body: 'If you suspect a person is in shock, call 108 or your local emergency number. Then immediately take the following steps:',
      imgUrl: require('../assets/images/108.png'),
    },
    {
      title: 'Lay the person down and keep still',
      body: 'Loosen tight clothing and, if needed, cover the person with a blanket to prevent chilling',
      imgUrl: require('../assets/images/shock-aid.png'),
    },
    {
      title: 'Begin CPR',
      body: 'Begin CPR if the person shows no signs of life, such as not breathing, coughing or moving.',
      imgUrl: require('../assets/images/cpr.jpg'),
    },
    {
      title: 'Avoid consuming anything',
      body: "Don't let the person eat or drink anything.",
      imgUrl: require('../assets/images/donteat.png'),
    },
  ],
  choking: [
    {
      title: 'Call 108 ambulance',
      body: 'Get emergency help if there is a severe airway obstruction or if the patient is unconscious.',
      imgUrl: require('../assets/images/108.png'),
    },
    {
      title: 'Encourage coughing',
      body: "If the person can't speak or cough,give back blows as:\n1.Stand behind the person\n2.Bend the person forward\n3.Give 5 firm blows between the shoulder blades with your hand.",
      imgUrl: require('../assets/images/coughing.jpg'),
    },
    {
      title: 'Chest thrusts',
      body: "If the object doesn't come out,put both arms around the person so your hands meet in front.Make a fist.Give five abdominal thrusts by pulling your fist inwards and upwards.",
      imgUrl: require('../assets/images/fiveblows.jpg'),
    },
    {
      title: 'Give CPR',
      body: 'If the person gets unconscious,lay down the person and start giving CPR.',
      imgUrl: require('../assets/images/cpr.jpg'),
    },
  ],
  dog: [
    {
      title: 'Look out for dangers',
      body: 'Check for danger to Yourself / Bystanders / Victims.Also ensure if the area is safe of any potential hazards.',
      imgUrl: require('../assets/images/survey.png'),
    },
    {
      title: 'Stop the bleeding',
      body: 'In case of bleeding,stop the bleeding by putting direct pressure on the wound.',
      imgUrl: require('../assets/images/stop-blood.jpg'),
    },
    {
      title: 'Avoid direct contact',
      body: "Make sure to wash your hands and cover them using clean plastic bag or gloves.Try to avoid coming in contact with patient's blood",
      imgUrl: require('../assets/images/dogbite.png'),
    },
    {
      title: 'Wash the wound',
      body: 'Flush the bite wound with clean water and soap (if available) for 10-15 minutes.',
      imgUrl: require('../assets/images/wash-wound.jpg'),
    },
    {
      title: 'Cover the wound',
      body: 'Apply an anti-bacterial ointment on the bite area.Cover the wound with a clean and dry cloth.',
      imgUrl: require('../assets/images/coverwound.jpg'),
    },

    {
      title: 'Call 108 ambulance',
      body: 'Always refer the person to a healthcare facility immediately for further treatment if possible exposure to rabies is suspected',
      imgUrl: require('../assets/images/108.png'),
    },
  ],
  faint: [
    {
      title: 'Shift the victim to a safer place',
      body: 'Loosen tight clothng,lay down the victim in a comfortable state to recover.',
      imgUrl: require('../assets/images/recovery1.png'),
    },
    {
      title: 'Check for consciousness',
      body: "Check if the person responds or not.If he doesn't ,do not try to change the body position - there might be injuries to head,neck or back.",
      imgUrl: require('../assets/images/breathes.jpg'),
    },
    {
      title: 'Call 108 ambulance',
      body: 'Always refer the person to a healthcare facility immediately for further treatment',
      imgUrl: require('../assets/images/callhelp.jpg'),
    },
    {
      title: 'Begin CPR',
      body: "If the person isn't breathing,start CPR immediately and contact healthcare facility.",
      imgUrl: require('../assets/images/cpr.jpg'),
    },
  ],
  snake: [
    {
      title: 'Dangers if any',
      body: 'Check for danger to Yourself / Bystanders / Victims.Also ensure if the area is safe of any potential hazards.',
      imgUrl: require('../assets/images/survey.png'),
    },
    {
      title: 'Call 108 ambulance',
      body: 'Always refer the person to a healthcare facility immediately for further treatment',
      imgUrl: require('../assets/images/callhelp.jpg'),
    },
    {
      title: 'Reassure the patient',
      body: 'Help the patient to get into a comfortable position and minimise their movement.Remove rings, watch,tight clothing that are worn on the bitten limb.',
      imgUrl: require('../assets/images/recover.png'),
    },
    {
      title: 'Be careful with the wound',
      body: 'Wash the wound with soap and water and do not try to cut it open.Do not apply ice or immerse the wound in water.',
      imgUrl: require('../assets/images/wash-bite.jpg'),
    },
    {
      title: 'Cover the wound',
      body: 'Place a wound dressing over the wound with 10 cm heavy crepe roller bandage,if available.Place a mark on bandage to identify the bite location.',
      imgUrl: require('../assets/images/snakebite-bandage.jpg'),
    },
    {
      title: 'Avoid contact with the wound',
      body: 'Do not suck out the venom.Do not apply herbs on the wound.Do not apply a torniquet.',
      imgUrl: require('../assets/images/suck-bite.png'),
    },
    {
      title: 'Check for consciousness',
      body: 'If he stops breathing,start CPR.If he is unconscious but breathing,put him in the recovery position.',
      imgUrl: require('../assets/images/breathes.jpg'),
    },
  ],
  insect: [
    {
      title: 'Remove the sting',
      body: 'Immediately remove the sting to prevent more venom release.Scrape it out sideways with a iron key,bank card etc.Do not pinch the sting with tweezers as more venom gets released.',
      imgUrl: require('../assets/images/remove-sting.jpg'),
    },
    {
      title: 'Wash the wound',
      body: 'Wash the affected area with soap and water',
      imgUrl: require('../assets/images/wash-wound.jpg'),
    },
    {
      title: 'Cool the area',
      body: 'Apply a cold compress such as a cool,wet cloth or an ice pack to any swelling for at least 10 minutes.', 
      imgUrl: require('../assets/images/icepack.jpg'),
    },
    {
      title: 'Apply hydrocortisone',
      body: 'Apply a thin layer of hydrocortisone cream to minimize any reaction you might have.Honey can also be used.', 
      imgUrl: require('../assets/images/corisone.jpg'),
    },
    {
      title: 'Avoid contact with the wound',
      body: 'Avoid scratching the area or bursting any blisters,to reduce the risk of infection.If the victim is a child,then keep their fingernails short and clean.', 
      imgUrl: require('../assets/images/scratching.jpg'),
    },
    {
      title: 'Take antibiotics(as adviced)',
      body: 'For pain or discomfort over-the-counter painkillers such as paracetamol or ibuprofen.Not for children under age 16.',
      imgUrl: require('../assets/images/ibuprofen.jpg'),
    },
    {
      title: 'Get medical advice',
      body: 'Consult a medical facility if your symptoms do not improve or get worse,if there is a wound infection or the bitten area is in your mouth,throat or near your eyes.',
      imgUrl: require('../assets/images/callhelp.jpg'),
    },
    {
      title: 'Call 108 ambulance',
      body: 'Emergency treatment is needed if the victim has severe reaction symptoms such as:\n1.Difficulty Breathing\n2.Loss of consciousness\n3.Fast heart rate.',
      imgUrl: require('../assets/images/108.png'),
    },
  ],
  cat: [
    {
      title: 'Look out for dangers',
      body: 'Check for danger to Yourself / Bystanders / Victims.Also ensure if the area is safe of any potential hazards.',
      imgUrl: require('../assets/images/survey.png'),
    },
    {
      title: 'Stop the bleeding',
      body: 'In case of bleeding,stop the bleeding by putting direct pressure on the wound.',
      imgUrl: require('../assets/images/stop-blood.jpg'),
    },
    {
      title: 'Avoid direct contact',
      body: "Make sure to wash your hands and cover them using clean plastic bag or gloves.Try to avoid coming in contact with patient's blood",
      imgUrl: require('../assets/images/dogbite.png'),
    },
    {
      title: 'Wash the wound',
      body: 'Flush the bite wound with clean water and soap (if available) for 10-15 minutes.',
      imgUrl: require('../assets/images/wash-wound.jpg'),
    },
    {
      title: 'Cover the wound',
      body: 'Apply an anti-bacterial ointment on the bite area.Cover the wound with a clean and dry cloth.',
      imgUrl: require('../assets/images/coverwound.jpg'),
    },

    {
      title: 'Call 108 ambulance',
      body: 'Always refer the person to a healthcare facility immediately for further treatment if possible exposure to rabies is suspected',
      imgUrl: require('../assets/images/108.png'),
    },
  ],
  breathe: [
    {
      title: 'Advice for adults',
      body: 'This advice is for helping an adult.To help a baby who is unresponsive and not breathing please follow the convenient procedure',
      imgUrl: require('../assets/images/breathingproblem.jpg'),
    },
    {
      title: 'Check for breathing',
      body: "Check breathing by tilting patient's head back and looking and feeling for breaths.If not breathing,their chest and stomach will not move.",
      imgUrl: require('../assets/images/breathes.jpg'),
    },
    {
      title: 'Call 108 ambulance',
      body: 'Always refer the person to a healthcare facility immediately for further treatment.If you cannot call,get someone else to do it.',
      imgUrl: require('../assets/images/108.png'),
    },
    {
      title: 'Give CPR',
      body: 'Give chest compressions.Push firmly downwards in the middle of the chest and then release.This will help in blood circulation to vital parts.',
      imgUrl: require('../assets/images/cpr.jpg'),
    },
  ],
  burns: [
    {
      title: 'Determine risk factor',
      body: 'Inspect for the damage occured to the victim and act accordingly.',
      imgUrl: require('../assets/images/burn-level.jpg'),
    },
    {
      title: 'Call 108 ambulance',
      body: 'Seek immediate care for major burns which are deep,larger than 3 inches in diameter,begin swelling quickly.',
      imgUrl: require('../assets/images/108.png'),
    },
    {
      title: 'Move to a safer place',
      body: 'Protect the burned person from further harm by moving the victim away from the source of the burn.Do not try to remove clothing stuck in burn.',
      imgUrl: require('../assets/images/safe-place.jpg'),
    },
    {
      title: 'Check for breathing',
      body: "Check breathing by tilting patient's head back and looking and feeling for breaths.If not breathing,begin rescue breathing if you know how.",
      imgUrl: require('../assets/images/check-breathe.jpg'),
    },
    {
      title: 'Remove accessories',
      body: 'Remove jewellery,rings,belts or any tight items especially from the burned area and neck.Burned areas swell quickly.',
      imgUrl: require('../assets/images/watch.jpg'),
    },
    {
      title: 'Cover the burn',
      body: 'Loosely cover the area with gauze or a clean cloth.',
      imgUrl: require('../assets/images/cover-burn.jpg'),
    },
    {
      title: 'Cool the burn',
      body: 'Hold the area under cool(not cold) running water for minutes.For face burns,apply wet cloth.For mouth burns from hot food or drink,place an ice cube', 
      imgUrl: require('../assets/images/icepack.jpg'),
    },
    {
      title: 'Apply lotion',
      body: 'After the burn is cooled,apply a lotion, such as one with aloe vera or cocoa butter.This prevents drying and provides relief.', 
      imgUrl: require('../assets/images/aloevera.jpg'),
    },
    {
      title: 'Bandage the burn',
      body: 'Cover the burn with a clean bandage.Wrap it loosely,avoid putting pressure on burned skin.Bandaging protects blistered skin from air.', 
      imgUrl: require('../assets/images/coverwound.jpg'),
    },
    {
      title: 'Cautionary advice',
      body: 'If you pop blisters, this creates an open wound and makes you vulnerable to an infection. If the blisters burst on their own,wash the wound with soap and clean water,apply cream over the area.',
      imgUrl: require('../assets/images/blister.jpg'),
    },
  ],
  eye: [
    {
      title: 'Wash hands',
      body: 'Wash your hands with soap and water.Wash under nails and in between your fingers as well.',
      imgUrl: require('../assets/images/wash-hand.jpg'),
    },
    {
      title: 'Remove the object',
      body: 'Try to flush out the object out of your eye with a gentle stream of clean,warm water.Use an eye cup or a small,clean drinking glass.',
      imgUrl: require('../assets/images/eye-wash.jpg'),
    },
    {
      title: 'Remove contact lenses (if any)',
      body: 'It is best to remove the lens before cleaning the surface of the eye with water. Sometimes a foreign body can be stuck to the undersurface of the lens.',
      imgUrl: require('../assets/images/contact-lens.jpg'),
    },
    {
      title: 'Call for medical help',
      body: 'Seek immediate care if:\n1.Object is not removed by simple methods\n2.Pain,redness persists for a long time\n3.Object is embedded in the eye.',
      imgUrl: require('../assets/images/108.png'),
    },
  ],
};

export const homeCards = [
  {
    title: 'Heart Attack',
    tag: 'heart',
    imgUrl: require('../assets/images/heart.png'),
  },
  {
    title: 'Shock',
    tag: 'shock',
    imgUrl: require('../assets/images/shock.png'),
  },
  {
    title: 'Broken Bones',
    tag: 'bones',
    imgUrl: require('../assets/images/bone.png'),
  },
  {
    title: 'Cuts',
    tag: 'cuts',
    imgUrl: require('../assets/images/cut.png'),
  },
  {
    title: 'Sun Stroke',
    tag: 'heat',
    imgUrl: require('../assets/images/sun.png'),
  },
  {
    title: 'Fever',
    tag: 'fever',
    imgUrl: require('../assets/images/fever.png'),
  },
];

export const features = [
  {
    title: 'First Aid Kits',
    imgUrl: require('../assets/images/firstaid.png'),
    nav: 'Kits',
  },
  {
    title: 'Medical Vocab',
    imgUrl: require('../assets/images/Book.png'),
    nav: 'VocabTypes',
  },
];

export const allFirstAids = [
  {
    title: 'Heart Attack',
    tag: 'heart',
    imgUrl: require('../assets/images/heart.png'),
  },
  {
    title: 'Shock',
    tag: 'shock',
    imgUrl: require('../assets/images/shock.png'),
  },
  {
    title: 'Broken Bones',
    tag: 'bones',
    imgUrl: require('../assets/images/bone.png'),
  },
  {
    title: 'Cuts',
    tag: 'cuts',
    imgUrl: require('../assets/images/cut.png'),
  },
  {
    title: 'Sun Stroke',
    tag: 'heat',
    imgUrl: require('../assets/images/sun.png'),
  },
  {
    title: 'Fever',
    tag: 'fever',
    imgUrl: require('../assets/images/fever.png'),
  },
  {
    title: 'Choking',
    tag: 'choking',
    imgUrl: require('../assets/images/choked.png'),
  },
  {
    title: 'Eye Injury',
    tag: 'eye',
    imgUrl: require('../assets/images/eye.png'),
  },
  {
    title: 'Burns',
    tag: 'burns',
    imgUrl: require('../assets/images/burns.png'),
  },
  {
    title: 'Fainting',
    tag: 'faint',
    imgUrl: require('../assets/images/faint.png'),
  },
  {
    title: 'No Breathing',
    tag: 'breathe',
    imgUrl: require('../assets/images/breathing.png'),
  },
  {
    title: 'Dog Bites',
    tag: 'dog',
    imgUrl: require('../assets/images/dog.png'),
  },
  {
    title: 'Snake Bites',
    tag: 'snake',
    imgUrl: require('../assets/images/snake.png'),
  },
  {
    title: 'Cat Bites',
    tag: 'cat',
    imgUrl: require('../assets/images/cat.png'),
  },
  {
    title: 'Insect Bites',
    tag: 'insect',
    imgUrl: require('../assets/images/bee.png'),
  },
];

export const vocabTypes = [
  {
    title:'Diseases and Conditions',
    imgUrl: require('../assets/images/germs.png'),
    tag:'diseases',
  },
  {
    title:'Medical Slang',
    imgUrl: require('../assets/images/medical.png'),
    tag:'slang',
  },
  {
    title:'Procedures and Tests',
    imgUrl: require('../assets/images/injection.png'),
    tag:'procedures',
  },
  {
    title:'Tools and Equipment',
    imgUrl: require('../assets/images/stethoscope.png'),
    tag:'tools',
  },
];

export const vehicleTypes = [
  {
    title:'Two wheeler',
    imgUrl:require('../assets/images/Motorcycle.png'),
    tag:'twoWheeler',
  },
  {
    title:'Four wheeler',
    imgUrl:require('../assets/images/Car.png'),
    tag:'fourWheeler',
  },
  {
    title:'Truck',
    imgUrl:require('../assets/images/truck.png'),
    tag:'truck',
  },
  {
    title:'Bus',
    imgUrl:require('../assets/images/Bus.png'),
    tag:'bus',
  },
];

export const travelTypes = [
  {
    title:'Mountain',
    imgUrl:require('../assets/images/mountain.png'),
    tag:'mountain',
  },
  {
    title:'Beach',
    imgUrl:require('../assets/images/beach.png'),
    tag:'beach',
  },
  {
    title:'Desert',
    imgUrl:require('../assets/images/desert.png'),
    tag:'desert',
  },
  {
    title:'Forest',
    imgUrl:require('../assets/images/forest.png'),
    tag: 'forest',
  },
  {
    title:'Plain',
    imgUrl:require('../assets/images/plain.png'),
    tag:'plain'
  },
];

export const kit = [
  {
    name: 'Daily Commute Kit',
    imgUrl: require('../assets/images/travelfirstaid.png'),
    desc:"Daily Commute Kit contains the first aid materials necessary for your local travel needs. It is never recommended to use any medicine without Doctor's consultation.",
    type:'dailykit'
  },
  {
    name: 'Basic Kit',
    imgUrl: require('../assets/images/basickit.png'),
    desc: "Basic Kit contains the first aid materials necessary for your daily home needs. It is never recommended to use any medicine without Doctor's consultation.",
    type:'basickit'
  },
  {
    name: 'Vehicle Kit',
    imgUrl: require('../assets/images/basickit.png'),
    desc: "Vehicle Kit contains the first aid materials necessary for your vehicle travel and accident needs. It is never recommended to use any medicine without Doctor's consultation.",
    type:'vehiclekit'
  },
  {
    name: 'Travel Kit',
    imgUrl: require('../assets/images/basickit.png'),
    desc: "Travel Kit contains the first aid materials necessary for your Tourism and Outdoor Emergency needs. It is never recommended to use any medicine without Doctor's consultation.",
    type:'travelkit'
  },
  {
    name: 'Office Kit',
    imgUrl: require('../assets/images/basickit.png'),
    desc: "Office Kit contains the first aid materials necessary for office and employees. It is never recommended to use any medicine without Doctor's consultation.",
    type:'officekit'
  },
  {
    name: 'Industrial Kit',
    imgUrl: require('../assets/images/basickit.png'),
    desc: "Industrial Kit contains the first aid materials necessary for manufacturing and production based industry. It is never recommended to use any medicine without Doctor's consultation.",
    type:'industrykit'
  },
];

export const kitTypes = {
  basickit : [
    { id: 1,txt: 'Antiseptics Cream', isChecked: false},
    { id: 2,txt: 'Bandages', isChecked: false},
    { id: 3,txt: 'Gauze', isChecked: false},
    { id: 4,txt: 'Cotton balls', isChecked: false},
    { id: 5,txt: 'Adhesive Tape', isChecked: false},
    { id: 6,txt: 'Scissors', isChecked: false},
    { id: 7,txt: 'Dettol', isChecked: false},
    { id: 8,txt: 'Stomach Ache Medicine', isChecked: false},
    { id: 9,txt: 'Head Ache Medicine', isChecked: false},
    { id: 10,txt: 'Allergies Medicine', isChecked: false},
    { id: 11,txt: 'Pain Killer Medicine', isChecked: false},
    { id: 12,txt: 'Loose Motion Medicine', isChecked: false},
    { id: 13,txt: 'Vomit Medicine', isChecked: false},
    { id: 14,txt: 'Fever Medicine', isChecked: false},
    { id: 15,txt: 'Antacid Medicine', isChecked: false},
    { id: 16,txt: 'Instant Hot or Cold Pack', isChecked: false},
    { id: 17,txt: 'Cough Syrup', isChecked: false},
    { id: 18,txt: 'Cold Medicine', isChecked: false},
    { id: 19,txt: 'Burn Creams', isChecked: false},
    { id: 20,txt: 'Move Spray', isChecked: false},
    { id: 21,txt: 'Eye Drop', isChecked: false},
    { id: 22,txt: 'Ear Drop', isChecked: false},
    { id: 23,txt: 'Nasal Spray', isChecked: false},
    { id: 24,txt: 'Antibiotic Ointment', isChecked: false},
    { id: 25,txt: 'Antibiotic Medicine', isChecked: false},
    { id: 26,txt: 'Thermometer', isChecked: false},
    { id: 27,txt: 'Blood Pressure Monitor', isChecked: false},
    { id: 28,txt: 'Weighing Machine', isChecked: false},
    { id: 29,txt: 'Oximeter', isChecked: false},
    { id: 30,txt: 'Hand Sanitizer', isChecked: false},
    { id: 31,txt: 'Aspirin', isChecked: false},
  ],
  officekit : [
    { id: 1,txt: 'First Aid Guide', isChecked: false},
    { id: 2,txt: 'Antiseptics Cream', isChecked: false},
    { id: 3,txt: 'Bandages', isChecked: false},
    { id: 4,txt: 'Gauze', isChecked: false},
    { id: 5,txt: 'Cotton balls', isChecked: false},
    { id: 6,txt: 'Adhesive Tape', isChecked: false},
    { id: 7,txt: 'Scissors', isChecked: false},
    { id: 8,txt: 'Dettol', isChecked: false},
    { id: 9,txt: 'Stomach Ache Medicine', isChecked: false},
    { id: 10,txt: 'Head Ache Medicine', isChecked: false},
    { id: 11,txt: 'Allergies Medicine', isChecked: false},
    { id: 12,txt: 'Pain Killer Medicine', isChecked: false},
    { id: 13,txt: 'Loose Motion Medicine', isChecked: false},
    { id: 14,txt: 'Vomit Medicine', isChecked: false},
    { id: 15,txt: 'Fever Medicine', isChecked: false},
    { id: 16,txt: 'Antacid Medicine', isChecked: false},
    { id: 17,txt: 'Instant Hot or Cold Pack', isChecked: false},
    { id: 18,txt: 'Cough Syrup', isChecked: false},
    { id: 19,txt: 'Cold Medicine', isChecked: false},
    { id: 20,txt: 'Burn Creams', isChecked: false},
    { id: 21,txt: 'Move Spray', isChecked: false},
    { id: 22,txt: 'Eye Drop', isChecked: false},
    { id: 23,txt: 'Ear Drop', isChecked: false},
    { id: 24,txt: 'Nasal Spray', isChecked: false},
    { id: 25,txt: 'Antibiotic Ointment', isChecked: false},
    { id: 26,txt: 'Antibiotic Medicine', isChecked: false},
    { id: 27,txt: 'Thermometer', isChecked: false},
    { id: 28,txt: 'Blood Pressure Monitor', isChecked: false},
    { id: 29,txt: 'Oximeter', isChecked: false},
    { id: 30,txt: 'Hand Sanitizer', isChecked: false},
    { id: 31,txt: 'Aspirin', isChecked: false},
  ],
  dailykit : [
    {id: 1,txt: 'Hand Sanitizer', isChecked: false},
    {id: 2,txt: 'Mask', isChecked: false},
    {id: 3,txt: 'Stomach Ache Medicine', isChecked: false},
    {id: 4,txt: 'Head Ache Medicine', isChecked: false},
    {id: 5,txt: 'Allergies Medicine', isChecked: false},
    {id: 6,txt: 'Pain Killer Medicine', isChecked: false},
    {id: 7,txt: 'Loose Motion Medicine', isChecked: false},
    {id: 8,txt: 'Vomit Medicine', isChecked: false},
    {id: 9,txt: 'Antacid Medicine', isChecked: false},
    {id: 10,txt: 'Your Daily Medication', isChecked: false},
  ],
  industrykit : [
    { id: 1,txt: 'First Aid Guide', isChecked: false},
    { id: 2,txt: 'Antiseptics Cream', isChecked: false},
    { id: 3,txt: 'Bandages', isChecked: false},
    { id: 4,txt: 'Gauze', isChecked: false},
    { id: 5,txt: 'Cotton balls', isChecked: false},
    { id: 6,txt: 'Adhesive Tape', isChecked: false},
    { id: 7,txt: 'Scissors', isChecked: false},
    { id: 8,txt: 'Dettol', isChecked: false},
    { id: 9,txt: 'Stomach Ache Medicine', isChecked: false},
    { id: 10,txt: 'Head Ache Medicine', isChecked: false},
    { id: 11,txt: 'Allergies Medicine', isChecked: false},
    { id: 12,txt: 'Pain Killer Medicine', isChecked: false},
    { id: 13,txt: 'Loose Motion Medicine', isChecked: false},
    { id: 14,txt: 'Vomit Medicine', isChecked: false},
    { id: 15,txt: 'Fever Medicine', isChecked: false},
    { id: 16,txt: 'Antacid Medicine', isChecked: false},
    { id: 17,txt: 'Instant Hot or Cold Pack', isChecked: false},
    { id: 18,txt: 'Cough Syrup', isChecked: false},
    { id: 19,txt: 'Cold Medicine', isChecked: false},
    { id: 20,txt: 'Burn Creams', isChecked: false},
    { id: 21,txt: 'Move Spray', isChecked: false},
    { id: 22,txt: 'Eye Drop', isChecked: false},
    { id: 23,txt: 'Ear Drop', isChecked: false},
    { id: 24,txt: 'Nasal Spray', isChecked: false},
    { id: 25,txt: 'Antibiotic Ointment', isChecked: false},
    { id: 26,txt: 'Antibiotic Medicine', isChecked: false},
    { id: 27,txt: 'Thermometer', isChecked: false},
    { id: 28,txt: 'Blood Pressure Monitor', isChecked: false},
    { id: 29,txt: 'Oximeter', isChecked: false},
    { id: 30,txt: 'Hand Sanitizer', isChecked: false},
    { id: 31,txt: 'Aspirin', isChecked: false},
    { id: 32,txt: 'Breathing Barrier', isChecked: false},
    { id: 33,txt: 'Gel Soaked Burn Dressing', isChecked: false},
    { id: 34,txt: 'Eye Covering (with attachment)', isChecked: false},
    { id: 35,txt: 'Eye/Skin Wash', isChecked: false},
    { id: 36,txt: 'Medical Exam Gloves', isChecked: false},
    { id: 37,txt: 'Sterile Pad', isChecked: false},
    { id: 38,txt: 'Trauma Pad', isChecked: false},
    { id: 39,txt: 'Tourniquet', isChecked: false},
    { id: 40,txt: 'Triangular Bandage', isChecked: false},
  ],
  vehiclekit:[
  ],
  travelkit:[
  ],
  twoWheeler : [
    { id: 1,txt: 'Antiseptics Cream', isChecked: false},
    { id: 2,txt: 'Bandages', isChecked: false},
    { id: 3,txt: 'Gauze', isChecked: false},
    { id: 4,txt: 'Cotton balls', isChecked: false},
    { id: 5,txt: 'Adhesive Tape', isChecked: false},
    { id: 6,txt: 'Scissors', isChecked: false},
    { id: 7,txt: 'Dettol', isChecked: false},
    { id: 8,txt: 'Burn Creams', isChecked: false},
    { id: 9,txt: 'Antibiotic Ointment', isChecked: false},
    { id: 10,txt: 'Antibiotic Medicine', isChecked: false},
    { id: 11,txt: 'Spare Specs (if applicable)', isChecked: false},
  ],
  fourWheeler : [
    { id: 1,txt: 'Antiseptics Cream', isChecked: false},
    { id: 2,txt: 'Bandages', isChecked: false},
    { id: 3,txt: 'Gauze', isChecked: false},
    { id: 4,txt: 'Cotton balls', isChecked: false},
    { id: 5,txt: 'Adhesive Tape', isChecked: false},
    { id: 6,txt: 'Scissors', isChecked: false},
    { id: 7,txt: 'Dettol', isChecked: false},
    { id: 8,txt: 'Burn Creams', isChecked: false},
    { id: 9,txt: 'Antibiotic Ointment', isChecked: false},
    { id: 10,txt: 'Antibiotic Medicine', isChecked: false},
    { id: 11,txt: 'Spare Specs (if applicable)', isChecked: false},
  ],
  truck : [
    { id: 1,txt: 'Antiseptics Cream', isChecked: false},
    { id: 2,txt: 'Bandages', isChecked: false},
    { id: 3,txt: 'Gauze', isChecked: false},
    { id: 4,txt: 'Cotton balls', isChecked: false},
    { id: 5,txt: 'Adhesive Tape', isChecked: false},
    { id: 6,txt: 'Scissors', isChecked: false},
    { id: 7,txt: 'Dettol', isChecked: false},
    { id: 8,txt: 'Burn Creams', isChecked: false},
    { id: 9,txt: 'Antibiotic Ointment', isChecked: false},
    { id: 10,txt: 'Antibiotic Medicine', isChecked: false},
    { id: 11,txt: 'Spare Specs (if applicable)', isChecked: false},
  ],
  bus : [
    { id: 1,txt: 'Antiseptics Cream', isChecked: false},
    { id: 2,txt: 'Bandages', isChecked: false},
    { id: 3,txt: 'Gauze', isChecked: false},
    { id: 4,txt: 'Cotton balls', isChecked: false},
    { id: 5,txt: 'Adhesive Tape', isChecked: false},
    { id: 6,txt: 'Scissors', isChecked: false},
    { id: 7,txt: 'Dettol', isChecked: false},
    { id: 8,txt: 'Burn Creams', isChecked: false},
    { id: 9,txt: 'Antibiotic Ointment', isChecked: false},
    { id: 10,txt: 'Antibiotic Medicine', isChecked: false},
    { id: 11,txt: 'Spare Specs (if applicable)', isChecked: false},
  ],
  mountain : [
    { id: 1,txt: 'Book on first aid', isChecked: false},
    { id: 2,txt: 'Insect repellant', isChecked: false},
    { id: 3,txt: 'Sunscreen', isChecked: false},
    { id: 4,txt: 'Tweezers', isChecked: false},
    { id: 5,txt: 'Diamox (for altitude sickness)', isChecked: false},
    { id: 6,txt: 'Sunglasses', isChecked: false},
    { id: 7,txt: 'Lip-gloss', isChecked: false},
    { id: 8,txt: 'Antiseptics Cream', isChecked: false},
    { id: 9,txt: 'Bandages', isChecked: false},
    { id: 10,txt: 'Gauze', isChecked: false},
    { id: 11,txt: 'Cotton balls', isChecked: false},
    { id: 12,txt: 'Adhesive Tape', isChecked: false},
    { id: 13,txt: 'Scissors', isChecked: false},
    { id: 14,txt: 'Dettol', isChecked: false},
    { id: 15,txt: 'Stomach Ache Medicine', isChecked: false},
    { id: 16,txt: 'Head Ache Medicine', isChecked: false},
    { id: 17,txt: 'Allergies Medicine', isChecked: false},
    { id: 18,txt: 'Pain Killer Medicine', isChecked: false},
    { id: 19,txt: 'Loose Motion Medicine', isChecked: false},
    { id: 20,txt: 'Vomit Medicine', isChecked: false},
    { id: 21,txt: 'Fever Medicine', isChecked: false},
    { id: 22,txt: 'Antacid Medicine', isChecked: false},
    { id: 23,txt: 'Instant Hot or Cold Pack', isChecked: false},
    { id: 24,txt: 'Cough Syrup', isChecked: false},
    { id: 25,txt: 'Cold Medicine', isChecked: false},
    { id: 26,txt: 'Burn Creams', isChecked: false},
    { id: 27,txt: 'Move Spray', isChecked: false},
    { id: 28,txt: 'Eye Drop', isChecked: false},
    { id: 29,txt: 'Ear Drop', isChecked: false},
    { id: 30,txt: 'Nasal Spray', isChecked: false},
    { id: 31,txt: 'Antibiotic Ointment', isChecked: false},
    { id: 32,txt: 'Antibiotic Medicine', isChecked: false},
    { id: 33,txt: 'Thermometer', isChecked: false},
    { id: 34,txt: 'Blood Pressure Monitor', isChecked: false},
    { id: 35,txt: 'Oximeter', isChecked: false},
    { id: 36,txt: 'Hand Sanitizer', isChecked: false},
    { id: 37,txt: 'Aspirin', isChecked: false},
  ],
  beach:[
    { id: 1,txt: 'Book on first aid', isChecked: false},
    { id: 2,txt: 'Insect repellant', isChecked: false},
    { id: 3,txt: 'Sunscreen', isChecked: false},
    { id: 4,txt: 'Tweezers', isChecked: false},
    { id: 5,txt: 'Meclizine (for motion sickness)', isChecked: false},
    { id: 6,txt: 'Antiseptics Cream', isChecked: false},
    { id: 7,txt: 'Bandages', isChecked: false},
    { id: 8,txt: 'Gauze', isChecked: false},
    { id: 9,txt: 'Cotton balls', isChecked: false},
    { id: 10,txt: 'Adhesive Tape', isChecked: false},
    { id: 11,txt: 'Scissors', isChecked: false},
    { id: 12,txt: 'Dettol', isChecked: false},
    { id: 13,txt: 'Stomach Ache Medicine', isChecked: false},
    { id: 14,txt: 'Head Ache Medicine', isChecked: false},
    { id: 15,txt: 'Allergies Medicine', isChecked: false},
    { id: 16,txt: 'Pain Killer Medicine', isChecked: false},
    { id: 17,txt: 'Loose Motion Medicine', isChecked: false},
    { id: 18,txt: 'Vomit Medicine', isChecked: false},
    { id: 19,txt: 'Fever Medicine', isChecked: false},
    { id: 20,txt: 'Antacid Medicine', isChecked: false},
    { id: 21,txt: 'Instant Hot or Cold Pack', isChecked: false},
    { id: 22,txt: 'Cough Syrup', isChecked: false},
    { id: 23,txt: 'Cold Medicine', isChecked: false},
    { id: 24,txt: 'Burn Creams', isChecked: false},
    { id: 25,txt: 'Move Spray', isChecked: false},
    { id: 26,txt: 'Eye Drop', isChecked: false},
    { id: 27,txt: 'Ear Drop', isChecked: false},
    { id: 28,txt: 'Nasal Spray', isChecked: false},
    { id: 29,txt: 'Antibiotic Ointment', isChecked: false},
    { id: 30,txt: 'Antibiotic Medicine', isChecked: false},
    { id: 31,txt: 'Thermometer', isChecked: false},
    { id: 32,txt: 'Blood Pressure Monitor', isChecked: false},
    { id: 33,txt: 'Oximeter', isChecked: false},
    { id: 34,txt: 'Hand Sanitizer', isChecked: false},
    { id: 35,txt: 'Aspirin', isChecked: false},
  ],
  plain:[
    { id: 1,txt: 'Book on first aid', isChecked: false},
    { id: 2,txt: 'Insect repellant', isChecked: false},
    { id: 3,txt: 'Sunscreen', isChecked: false},
    { id: 4,txt: 'Tweezers', isChecked: false},
    { id: 5,txt: 'Antiseptics Cream', isChecked: false},
    { id: 6,txt: 'Bandages', isChecked: false},
    { id: 7,txt: 'Gauze', isChecked: false},
    { id: 8,txt: 'Cotton balls', isChecked: false},
    { id: 9,txt: 'Adhesive Tape', isChecked: false},
    { id: 10,txt: 'Scissors', isChecked: false},
    { id: 11,txt: 'Dettol', isChecked: false},
    { id: 12,txt: 'Stomach Ache Medicine', isChecked: false},
    { id: 13,txt: 'Head Ache Medicine', isChecked: false},
    { id: 14,txt: 'Allergies Medicine', isChecked: false},
    { id: 15,txt: 'Pain Killer Medicine', isChecked: false},
    { id: 16,txt: 'Loose Motion Medicine', isChecked: false},
    { id: 17,txt: 'Vomit Medicine', isChecked: false},
    { id: 18,txt: 'Fever Medicine', isChecked: false},
    { id: 19,txt: 'Antacid Medicine', isChecked: false},
    { id: 20,txt: 'Instant Hot or Cold Pack', isChecked: false},
    { id: 21,txt: 'Cough Syrup', isChecked: false},
    { id: 22,txt: 'Cold Medicine', isChecked: false},
    { id: 23,txt: 'Burn Creams', isChecked: false},
    { id: 24,txt: 'Move Spray', isChecked: false},
    { id: 25,txt: 'Eye Drop', isChecked: false},
    { id: 26,txt: 'Ear Drop', isChecked: false},
    { id: 27,txt: 'Nasal Spray', isChecked: false},
    { id: 28,txt: 'Antibiotic Ointment', isChecked: false},
    { id: 29,txt: 'Antibiotic Medicine', isChecked: false},
    { id: 30,txt: 'Thermometer', isChecked: false},
    { id: 31,txt: 'Blood Pressure Monitor', isChecked: false},
    { id: 32,txt: 'Oximeter', isChecked: false},
    { id: 33,txt: 'Hand Sanitizer', isChecked: false},
    { id: 34,txt: 'Aspirin', isChecked: false},
  ],
  desert:[
    { id: 1,txt: 'Book on first aid', isChecked: false},
    { id: 2,txt: 'Insect repellant', isChecked: false},
    { id: 3,txt: 'Sunscreen', isChecked: false},
    { id: 4,txt: 'Tweezers', isChecked: false},
    { id: 5,txt: 'Sunglasses', isChecked: false},
    { id: 6,txt: 'Lip-gloss', isChecked: false},
    { id: 7,txt: 'Water Purification Tablets', isChecked: false},
    { id: 8,txt: 'Antiseptics Cream', isChecked: false},
    { id: 9,txt: 'Bandages', isChecked: false},
    { id: 10,txt: 'Gauze', isChecked: false},
    { id: 11,txt: 'Cotton balls', isChecked: false},
    { id: 12,txt: 'Adhesive Tape', isChecked: false},
    { id: 13,txt: 'Scissors', isChecked: false},
    { id: 14,txt: 'Dettol', isChecked: false},
    { id: 15,txt: 'Stomach Ache Medicine', isChecked: false},
    { id: 16,txt: 'Head Ache Medicine', isChecked: false},
    { id: 17,txt: 'Allergies Medicine', isChecked: false},
    { id: 18,txt: 'Pain Killer Medicine', isChecked: false},
    { id: 19,txt: 'Loose Motion Medicine', isChecked: false},
    { id: 20,txt: 'Vomit Medicine', isChecked: false},
    { id: 21,txt: 'Fever Medicine', isChecked: false},
    { id: 22,txt: 'Antacid Medicine', isChecked: false},
    { id: 23,txt: 'Instant Hot or Cold Pack', isChecked: false},
    { id: 24,txt: 'Cough Syrup', isChecked: false},
    { id: 25,txt: 'Cold Medicine', isChecked: false},
    { id: 26,txt: 'Burn Creams', isChecked: false},
    { id: 27,txt: 'Move Spray', isChecked: false},
    { id: 28,txt: 'Eye Drop', isChecked: false},
    { id: 29,txt: 'Ear Drop', isChecked: false},
    { id: 30,txt: 'Nasal Spray', isChecked: false},
    { id: 31,txt: 'Antibiotic Ointment', isChecked: false},
    { id: 32,txt: 'Antibiotic Medicine', isChecked: false},
    { id: 33,txt: 'Thermometer', isChecked: false},
    { id: 34,txt: 'Blood Pressure Monitor', isChecked: false},
    { id: 35,txt: 'Oximeter', isChecked: false},
    { id: 36,txt: 'Hand Sanitizer', isChecked: false},
    { id: 37,txt: 'Aspirin', isChecked: false},
  ],
  forest:[
    { id: 1,txt: 'Book on first aid', isChecked: false},
    { id: 2,txt: 'Insect repellant', isChecked: false},
    { id: 3,txt: 'Sunscreen', isChecked: false},
    { id: 4,txt: 'Tweezers', isChecked: false},
    { id: 5,txt: 'Knife', isChecked: false},
    { id: 6,txt: 'Hydrogen peroxide (for leech)', isChecked: false},
    { id: 7,txt: 'Antiseptics Cream', isChecked: false},
    { id: 8,txt: 'Bandages', isChecked: false},
    { id: 9,txt: 'Gauze', isChecked: false},
    { id: 10,txt: 'Cotton balls', isChecked: false},
    { id: 11,txt: 'Adhesive Tape', isChecked: false},
    { id: 12,txt: 'Scissors', isChecked: false},
    { id: 13,txt: 'Dettol', isChecked: false},
    { id: 14,txt: 'Stomach Ache Medicine', isChecked: false},
    { id: 15,txt: 'Head Ache Medicine', isChecked: false},
    { id: 16,txt: 'Allergies Medicine', isChecked: false},
    { id: 17,txt: 'Pain Killer Medicine', isChecked: false},
    { id: 18,txt: 'Loose Motion Medicine', isChecked: false},
    { id: 19,txt: 'Vomit Medicine', isChecked: false},
    { id: 20,txt: 'Fever Medicine', isChecked: false},
    { id: 21,txt: 'Antacid Medicine', isChecked: false},
    { id: 22,txt: 'Instant Hot or Cold Pack', isChecked: false},
    { id: 23,txt: 'Cough Syrup', isChecked: false},
    { id: 24,txt: 'Cold Medicine', isChecked: false},
    { id: 25,txt: 'Burn Creams', isChecked: false},
    { id: 26,txt: 'Move Spray', isChecked: false},
    { id: 27,txt: 'Eye Drop', isChecked: false},
    { id: 28,txt: 'Ear Drop', isChecked: false},
    { id: 29,txt: 'Nasal Spray', isChecked: false},
    { id: 30,txt: 'Antibiotic Ointment', isChecked: false},
    { id: 31,txt: 'Antibiotic Medicine', isChecked: false},
    { id: 32,txt: 'Thermometer', isChecked: false},
    { id: 33,txt: 'Blood Pressure Monitor', isChecked: false},
    { id: 34,txt: 'Oximeter', isChecked: false},
    { id: 35,txt: 'Hand Sanitizer', isChecked: false},
    { id: 36,txt: 'Aspirin', isChecked: false},
  ]
};

export const medicalVocab = {
  diseases:[
    {
      title:'Acute',
      desc:'A condition that is often severe but starts and ends quickly',
      link:'https://www.youtube.com/watch?v=mQA0oVoGr78',
    },
    {
      title:'Angina',
      desc:'Intermittent chest pain normally caused by insufficient blood flow to the heart',
      link:'https://www.youtube.com/watch?v=JW9Ov74qo-8&ab_channel=MedicalDictionary',
    },
    {
      title:'Benign',
      desc:'Refers to a tumor that is neither cancerous nor malignant',
      link:'https://www.youtube.com/watch?v=wAe8s_vxUAk&ab_channel=MedicalDictionary',
    },
    {
      title:'Chronic',
      desc:'Describes a condition that is persistent or recurring',
      link:'https://www.youtube.com/watch?v=AGciwBrsKBQ&ab_channel=MedicalDictionary',
    },
    {
      title:'Edema',
      desc:'Swelling as a result of fluid retention or build-up',
      link:'https://www.youtube.com/watch?v=OQCJtBSHRhk&ab_channel=MedicalDictionary',
    },
    {
      title:'Embolism',
      desc:'A clot caused by blood, fat, air or other types of fluid, gas or foreign material',
      link:'https://www.youtube.com/watch?v=RgG4-Xn1VWM&ab_channel=MedicalDictionary',
    },
    {
      title:'Fracture',
      desc:'A cracked or broken bone',
      link:'https://www.youtube.com/watch?v=qV0gBZGzHMI&ab_channel=MedicalDictionary',
    },
    {
      title:'Hypertension',
      desc:'Unusually high blood pressure',
      link:'https://www.youtube.com/watch?v=y9O59FTCC6o&ab_channel=MedicalDictionary',
    },
    {
      title:'Hypotension',
      desc:'Unusually low blood pressure',
      link:'https://www.youtube.com/watch?v=wx7DYnD0mzY&ab_channel=MedicalDictionary',
    },
    {
      title:'Intravenous',
      desc:'Administration of medication or fluids by vein',
      link:'https://www.youtube.com/watch?v=4VqiVgY5AxQ&ab_channel=MedicalDictionary',
    },
    {
      title:'Lesion',
      desc:'Damage or change to tissue, such as a cut, a wound or a sore',
      link:'https://www.youtube.com/watch?v=a-Wl2iNTOcE&ab_channel=MedicalDictionary',
    },
    {
      title:'Malignant',
      desc:'Refers to the presence of cancerous cells in a tumor or growth',
      link:'https://www.youtube.com/watch?v=0r3CLbOi9KQ&ab_channel=MedicalDictionary',
    },
    {
      title:'Myocardial Infarction',
      desc:'Also known as a heart attack, where the heart is deprived of blood due to arterial blockage',
      link:'https://www.youtube.com/watch?v=7QS2VcHlla8&ab_channel=MedicalDictionary',
    },
    {
      title:'Remission',
      desc:'Describes a disease that is not getting worse',
      link:'https://www.youtube.com/watch?v=Sky0uY88_cM&ab_channel=MedicalDictionary',
    },
    {
      title:'Sepsis',
      desc:"An imbalance in the body's response to infection that injures the body's tissues and organs",
      link:'https://www.youtube.com/watch?v=zVisyNraRks&ab_channel=MedicalDictionary',
    },
    {
      title:'Thrombosis',
      desc:'A blood clot that forms inside a blood vessel restricting blood flow',
      link:'https://www.youtube.com/watch?v=nWmdG1D9dAI&ab_channel=MedicalDictionary',
    },
  ],
  slang:[
    {
      title:'Afib',
      desc:"Atrial fibrillation, irregular and rapid heartbeats",
      link:"https://www.youtube.com/watch?v=Sj5JFMuZ1kE&ab_channel=MedicalDictionary",
    },
    {
      title:'Bagging',
      desc:"Helping a patient breathe using a squeeze bag attached to a face mask",
      link:"https://www.youtube.com/watch?v=YefaOkZPS3A&ab_channel=Dr.ApurvaPopat",
    },
    {
      title:'C-section',
      desc:"Caesarian section, where a baby is delivered through an abdominal and uterine incision",
      link:"https://www.youtube.com/watch?v=T6wti3LAVK8&ab_channel=MedicalDictionary",
    },
    {
      title:'Detox',
      desc:"Detoxification, is the removal of toxins from the body, such as drugs or alcohol",
      link:"https://www.youtube.com/watch?v=lZeRMz27Ckk&ab_channel=MedicalDictionary",
    },
    {
      title:'Exam',
      desc:"Examination",
      link:"https://www.youtube.com/watch?v=PD9hWhOccUY&ab_channel=StrongMedicine",
    },
    {
      title:'Foley',
      desc:"A catheter inserted into the bladder to help with urinary drainage",
      link:"https://www.youtube.com/watch?v=pipyEZaMr5M&ab_channel=MedicalDictionary",
    },
    {
      title:'Nitro',
      desc:"Nitroglycerin",
      link:"https://www.youtube.com/watch?v=0744cD19RmQ&ab_channel=Medical101",
    },
    {
      title:'O Sign',
      desc:"A patient who is unconscious and open-mouthed",
      link:"https://www.youtube.com/watch?v=CgXmjHJqsT4&ab_channel=MedicalDictionary",
    },
    {
      title:"OD'd",
      desc:"Overdosed",
      link:"https://www.youtube.com/watch?v=vunfedn1dOw&ab_channel=Medical101",
    },
    {
      title:'Script',
      desc:"Prescription",
      link:"https://www.youtube.com/watch?v=aEYih7njaQU&ab_channel=MedicalDictionary",
    },
    {
      title:'Thready',
      desc:"Shallow and weak, particularly in reference to a person's pulse",
      link:"https://www.youtube.com/watch?v=nhAz84srBvg&ab_channel=Osmosis",
    },
    {
      title:'Tox Screen',
      desc:"A blood test to determine the type and quantity of drugs in the system",
      link:"https://www.youtube.com/watch?v=ZDB8Z-j-Ffk&ab_channel=HowToGastro",
    },
  ],
  procedures:[
    {
      title:'Appendectomy',
      desc:'Surgical procedure to remove the appendix',
      link:'https://www.youtube.com/watch?v=lrpK4DraQf0&ab_channel=MedicalDictionary',
    },
    {
      title:'Biopsy',
      desc:'Removal of a small tissue sample for testing',
      link:'https://www.youtube.com/watch?v=YChlPcSwCsA&ab_channel=MedicalDictionary',
    },
    {
      title:'Blood Culture',
      desc:'Test to reveal the existence of fungi or bacteria in the blood, possibly indicating an infection',
      link:'https://www.youtube.com/watch?v=Ha9q4ncWr8E&ab_channel=LabsforLifeProject',
    },
    {
      title:'Blood Swab',
      desc:'Taking a blood sample using a cotton-tipped stick',
      link:'https://www.youtube.com/watch?v=cIddzUYzUI4&ab_channel=LabsforLifeProject',
    },
    {
      title:'Coronary Bypass',
      desc:'Surgical transplant of a healthy blood vessel into the heart to bypass or replace an unhealthy vessel',
      link:'https://www.youtube.com/watch?v=3Nf6Q2skGOM&ab_channel=NucleusMedicalMedia',
    },
    {
      title:'Dialysis',
      desc:'Process to filter the blood, usually performed as a result of kidney failure',
      link:'https://www.youtube.com/watch?v=IQKQ4eoKfTg&ab_channel=NucleusMedicalMedia',
    },
    {
      title:'Fusion',
      desc:'Joining together adjacent bones or vertebrae to increase stability',
      link:'https://www.youtube.com/watch?v=WID1p_UJZIM&ab_channel=NucleusMedicalMedia',
    },
    {
      title:'Glucose Test',
      desc:'A test to discover the quantity of a particular type of sugar in the bloodstream',
      link:'https://www.youtube.com/watch?v=rMMpeLLgdgY&ab_channel=Diabetes.co.uk',
    },
    {
      title:'Hysterectomy',
      desc:'Surgical procedure to remove the uterus',
      link:'https://www.youtube.com/watch?v=hn8Jf6nfv7c&ab_channel=NucleusMedicalMedia',
    },
    {
      title:'Intubation',
      desc:'Medical insertion of a tube into the body, for example, into the throat to assist with breathing',
      link:'https://www.youtube.com/watch?v=WaG-kG2RMNc&ab_channel=MedicalDictionary',
    },
    {
      title:'Lead test',
      desc:'A test to reveal the quantity of lead in the bloodstream ',
      link:'https://www.youtube.com/watch?v=7UpcXKETWRU&ab_channel=WSUSpokane',
    },
    {
      title:'Lumbar Puncture',
      desc:'Drawing of cerebrospinal fluid from the lumbar region of the back using a hollow needle',
      link:'https://www.youtube.com/watch?v=LZqiu6PKrZU&ab_channel=DesignScience',
    },
    {
      title:'Spinal Tap',
      desc:'Drawing of cerebrospinal fluid from the lumbar region of the back using a hollow needle',
      link:'https://www.youtube.com/watch?v=O_RjwNMZws8&ab_channel=LarryMellick',
    },
    {
      title:'Mastectomy',
      desc:'Surgical procedure to remove part or all of the breast',
      link:'https://www.youtube.com/watch?v=mT74IWGN2bA&ab_channel=JohnsHopkinsMedicine',
    },
    {
      title:'Occult Blood Screen',
      desc:'Use of a chemically treated card or pad to test for blood hidden in a stool sample',
      link:'https://www.youtube.com/watch?v=z8d1LT0VnXI&ab_channel=LabsforLifeProject',
    },
    {
      title:'Ultrasound',
      desc:'Imaging produced by high-frequency sound waves, usually used to view internal organs',
      link:'https://www.youtube.com/watch?v=X8ab6NAIV5I&ab_channel=MedicalAidFilms-FilmsForLife',
    },
    {
      title:'X-ray',
      desc:'Use of high-energy electromagnetic radiation to create images of internal bones and organs',
      link:'https://www.youtube.com/watch?v=_KUmCNmpLeA&ab_channel=GEHealthcare',
    },
  ],
  tools:[
    {
      title:'Blood lancet',
      desc:'A double-edged blade or needle used to obtain blood samples',
      link:'https://www.youtube.com/watch?v=JPJ4l7QZ9eM&ab_channel=RegisteredNurseRN',
    },
    {
      title:'Defibrillator',
      desc:'A device that discharges an electric current to the heart to correct cardiac arrhythmia or arrest',
      link:'https://www.youtube.com/watch?v=8A0kljQU48U&ab_channel=BritishHeartFoundation',
    },
    {
      title:'Dialyser',
      desc:'A machine that replaces the function of the kidneys by removing solutes, excess water and toxins from the blood',
      link:'https://www.youtube.com/watch?v=9uCsTbfpN64&ab_channel=LeonThomas',
    },
    {
      title:'Endoscope',
      desc:'An optical instrument containing a tube with a lighted end used for internal examinations',
      link:'https://www.youtube.com/watch?v=F6hdQJdWFkk&ab_channel=CincinnatiChildren%27s',
    },
    {
      title:'Forceps',
      desc:'A hinged instrument, like scissors, used to grasp and hold objects',
      link:'https://www.youtube.com/watch?v=_InLgIcaNcA&ab_channel=TrialExhibits%2CInc.',
    },
    {
      title:'Hypodermic needle',
      desc:'A very thin, hollow needle used with a syringe to inject substances into the body or to extract blood',
      link:'https://www.youtube.com/watch?v=i1tbJuE-UmQ&ab_channel=DSCDocumentries',
    },
    {
      title:'Nebulizer',
      desc:'A device used to deliver medication in an aerosol form through inhalation',
      link:'https://www.youtube.com/watch?v=Ns7vZnhreYk&ab_channel=Ann%26RobertH.LurieChildren%27sHospitalofChicago',
    },
    {
      title:'Ophthalmoscope',
      desc:"An instrument used to examine the eye's fundus, retina and other structures",
      link:'https://www.youtube.com/watch?v=i-QTRoJiR5E&ab_channel=MoranCORE',
    },
    {
      title:'Otoscope',
      desc:'A device for examining the external ear cavity',
      link:'https://www.youtube.com/watch?v=FE0sot4OoAE&ab_channel=OxfordMedicalEducation',
    },
    {
      title:'Auriscope',
      desc:'A device for examining the external ear cavity',
      link:'https://www.youtube.com/watch?v=YZbk5Uel55E&ab_channel=DoctorO%27Donovan',
    },
    {
      title:'Pulse oximeter',
      desc:'A small device that clips to the finger, toe or earlobe used to measure blood oxygen saturation',
      link:'https://www.youtube.com/watch?v=N3MCvREORVA&ab_channel=Medinaz',
    },
    {
      title:'Reflex hammer',
      desc:'A specially designed hammer used to test deep tendon or motor reflexes',
      link:'https://www.youtube.com/watch?v=0sqCIzuotWo&ab_channel=StanfordMedicine25',
    },
    {
      title:'Speculum',
      desc:'An instrument used when examining body orifices to help widen the opening ',
      link:'https://www.youtube.com/watch?v=_RClZAGq1bY&ab_channel=narangmedical',
    },
    {
      title:'Spirometer',
      desc:'A device that measures the amount of air breathed in and out by the lungs',
      link:'https://www.youtube.com/watch?v=hQzNG89pESQ&ab_channel=NucleusMedicalMedia',
    },
    {
      title:'Splint',
      desc:'A tool for immobilizing and protecting displaced or injured body parts such as broken bones or dislocated joints',
      link:'https://www.youtube.com/watch?v=Ot7c3syPtr4&ab_channel=MonkeySee',
    },
    {
      title:'Stethoscope',
      desc:'A device for listening to the heartbeat or breathing',
      link:'https://www.youtube.com/watch?v=QWyK4jELnu8&ab_channel=StGeorge%27s%2CUniversityofLondon',
    },
    {
      title:'Ventilator',
      desc:'A machine that provides mechanical assistance with breathing',
      link:'https://www.youtube.com/watch?v=gk_Qf-JAL84&ab_channel=MedCram-MedicalLecturesExplainedCLEARLY',
    },
    
  ],
};